// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovetruCaseDataAccessLayer.Concrete;

#nullable disable

namespace MovetruCase.DataAccessLayer.Migrations
{
    [DbContext(typeof(MovetruContext))]
    [Migration("20240915114846_v0.2")]
    partial class v02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovetruCase.Entities.Entities.UserData", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("HeightAsCentimeter")
                        .HasColumnType("int");

                    b.Property<bool>("IsUserNewlyRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WeightAsKilogram")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("UserDatas");
                });

            modelBuilder.Entity("MovetruCaseEntities.Entities.DailyStepLog", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdateDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "CreationDate");

                    b.ToTable("DailyStepLogs");
                });

            modelBuilder.Entity("MovetruCaseEntities.Entities.DailyStepLog", b =>
                {
                    b.HasOne("MovetruCase.Entities.Entities.UserData", "UserData")
                        .WithMany("DailyStepLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("MovetruCase.Entities.Entities.UserData", b =>
                {
                    b.Navigation("DailyStepLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
